---
#
# Ansible managed
#
repository:
  description: Allow your system to use Lorax, the image builder.
  homepage: https://robertdebock.nl/
  topics: imagebuilder, ansible, molecule, tox, playbook, hacktoberfest
