---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="centos" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "kjS5xvZPFR3XMFUqsDX97TU4Ee5Vn0kaCGQFAH9RgukgU6OVApetlmDyYoPfUeZxm5/0RMukLuhp6SSd18f0byow18CbYXuod63AIab2hXHF8ir4Op81BpTUdmk+jCiugqjsUPXIxvVaeiLBiI0OsDBewPl5SVQMAUYUv3IMVnSfkJYOr/zOvSpZM9yPDZP2eyWpbb61q8Gx8rc8ziU3YE9gOVLQBpKNOkr6soN1G/RGRsR48eg8rfzB8Ti7TizvcCv+Z9XeB/R3fhG1MpHJlhgeo4eV6eJyTBO41RK+bbw+4HhB/CSAJs0Vi4K6smv1o7FD3y4hpDVRkdGHX2cUOt3Hrh97CdnEYxFPCtZLbtZN5xTp2KfLFoH1QJ/RBzG5Zf2ZUs5QZQ0lqKFebsWAH7+O7sPub92cLvVKZFVPIRVUin+3EzaVpEOz9VEZc/uy3WiBlx+5invL67Mo67t2Vu7RgP4+rky3Uyk0unRLgUii6IomZ6YukABgGHvsJOUO5lVStwRPaF0dxNpkaGRa0VUlefHVZbs5i50qK2P4AuHGnsv0AbgFOlxgPKehlzCLi1X5F8GnWCw3CGUe9sYg4IKiEGA7pUXN8A0eBHvMoQEFynyeLcfFg78+3EFLZMaK5DZRABOIsF+gpEF5i/LTfxLcNZU8ubpKSLuUwE6gy2E="
  email: false
