---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="centos" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "NVoaTm7RctpE9Vzd5UfvNpYIiX4THnhjR6J7ydisyORffD91vVR13UwHE4t+9XuU4YIMcr+lpzQFPbpNkkmIkxdfum3IiZQopkcbu2tp+i2lYyHTK0NyGFAuhB6aZ7NzlTbYVqHgCDcBCkBxaIEmmhy8A5yXO7Y6w3iEFq2+uRmFRQ50tipeRep8oy211Ch+HCRubx3JSK+xUf3D3A4Qd3BS0T6m3phV+9qtNzwNWWO1iYmZKTF/5U51Au68Zd2W9k6VUTJ0ckGzjruovkZBDeujFr3Ai27pO5Lsq9SthA4Ua/CcXqeZHSSDSm/2uZv7CtNH2EEAekcW+QfqEdhz+oEqPIpS4p/WwxBRps7Mkj5x57/0cWQUdmUN3H4YKv7RMjv8dNrLMiaPtp6wvhpFky6N7rDYdoX5g6+UuyzDKSNERFPOXgU59Xyb0my9NUCaAMKxzJ5r0A1xcCt6qmN7bXeqjhXebw6eGCL+8m5bpWH6qQgtXMG+RzeOPefmmR3ZzZghb3NbxVqJczOK6lil+Cvtl96pyI5XD2c6EGEtqv3kSDOt9sertca0j3X/1moVG2lNYE+IrxNP8wdzmr6t4womQlNLfiG2TfE1+JF77UZyHtY+7/z9K9uOzwNd9Rko8RGrCWR8+2ECDOJxxUobZPe3QslcJc15Wb9jeR4TGPY="
  email: false
