---
# tasks file for image_builder
- name: include assert.yml
  include_tasks: assert.yml

- name: install packages
  package:
    name: "{{ image_builder_packages }}"
    state: present
  register: image_builder_install_packages
  until: image_builder_install_packages is succeeded
  retries: 3
  notify:
    - restart service

- name: start and enable service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ image_builder_services }}"

- name: create blueprint
  template:
    src: blueprint.toml.j2
    dest: blueprint.toml
  notify:
    - push blueprint
    - start blueprint
